# Imports

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import cv2
import pydotplus

from sklearn               import metrics as mt
from sklearn               import tree    as tr
from sklearn.tree          import DecisionTreeRegressor
from sklearn.ensemble      import RandomForestRegressor
from IPython.display       import Image
from six                   import StringIO
from sklearn.linear_model  import LinearRegression
from sklearn.linear_model  import Lasso, Ridge, ElasticNet
from sklearn.preprocessing import PolynomialFeatures

# Carregando DataSet

In [3]:
df_x_train = pd.read_csv('dados_ensaio/ensaio_reg/dados_train/x_train.csv')
df_y_train = pd.read_csv('dados_ensaio/ensaio_reg/dados_train/y_train.csv')

df_x_val = pd.read_csv('dados_ensaio/ensaio_reg/daods_val/x_val.csv')
df_y_val = pd.read_csv('dados_ensaio/ensaio_reg/daods_val/y_val.csv')

df_x_test = pd.read_csv('dados_ensaio/ensaio_reg/dados_test/x_test.csv')
df_y_test = pd.read_csv('dados_ensaio/ensaio_reg/dados_test/y_test.csv')

# Observando os Dados

In [4]:
print(df_x_train.shape)
print(df_y_train.shape)

(10547, 13)
(10547, 1)

In [5]:
print(df_x_val.shape)
print(df_y_val.shape)

(4521, 13)
(4521, 1)

In [6]:
print(df_x_test.shape)
print(df_y_test.shape)

(3767, 13)
(3767, 1)

# Ensaios

Vamos medir a performance dos algortimos: Linear Regression, Decision Tree Regressor, Random Forest Regressor, Linear Regression Lasso, Linear Regression Ridge, Linear Regression Elastic Net, Polinomial Regression Lasso, Polinomial Regression Ridge e Polinomial Regression Elastic Net.

As métricas de performance serão: R2, MSE, RMSE, MAE e MAPE

Serão então 3 tabelas, para cada conjunto de dados, medindo Algoritmo x Métrica (10 x 5)

In [7]:
#definindo x e y
x_train = df_x_train
y_train = df_y_train

x_val = df_x_val
y_val = df_y_val

x_test = df_x_test
y_test = df_y_test

In [8]:
y_train.describe()

       song_popularity
count     10547.000000
mean         53.046961
std          21.864535
min           0.100000
25%          40.000000
50%          56.000000
75%          69.000000
max         100.000000

# Linear Regression

### LR - Val

In [9]:
model_lr = LinearRegression()
model_lr.fit(x_train, y_train)

y_pred = model_lr.predict(x_val)

tabela_result_lr = pd.DataFrame({
    'r2': [mt.r2_score(y_val, y_pred)],
    'mse' : [mt.mean_squared_error(y_val, y_pred)],
    'rmse' : [np.sqrt(mt.mean_squared_error(y_val, y_pred))],
    'mae' : [mt.mean_absolute_error(y_val, y_pred)],
    'mape' : [mt.mean_absolute_percentage_error(y_val, y_pred)]
})

tabela_result_lr.round(3)

     r2      mse    rmse    mae   mape
0  0.04  458.447  21.411  17.04  8.683

### LR - Train

In [10]:
model_lr = LinearRegression()
model_lr.fit(x_train, y_train)

y_pred = model_lr.predict(x_train)

tabela_result_lr = pd.DataFrame({
    'r2': [mt.r2_score(y_train, y_pred)],
    'mse' : [mt.mean_squared_error(y_train, y_pred)],
    'rmse' : [np.sqrt(mt.mean_absolute_error(y_train, y_pred))],
    'mae' : [mt.mean_absolute_error(y_train, y_pred)],
    'mape' : [mt.mean_absolute_percentage_error(y_train, y_pred)]
})

tabela_result_lr.round(3)

      r2      mse   rmse     mae   mape
0  0.046  455.996  4.123  16.998  8.653

### LR - Test

In [11]:
model_lr = LinearRegression()
model_lr.fit(x_train, y_train)

y_pred = model_lr.predict(x_test)

tabela_result_lr = pd.DataFrame({
    'r2': [mt.r2_score(y_test, y_pred)],
    'mse' : [mt.mean_squared_error(y_test, y_pred)],
    'rmse' : [np.sqrt(mt.mean_squared_error(y_test, y_pred))],
    'mae' : [mt.mean_absolute_error(y_test, y_pred)],
    'mape' : [mt.mean_absolute_percentage_error(y_test, y_pred)]
})

tabela_result_lr.round(3)

      r2      mse    rmse    mae   mape
0  0.052  461.428  21.481  17.13  8.522

# Linear Regression - Lasso e Ridge

Parâmetros: alpha e max_iter

### LR - Val

In [12]:
#achando os melhores parâmetros
alpha_range = [0.001, 0.01, 0.1, 1, 10, 100]
max_iter_range = [100, 500, 1000, 5000]

# ---- Lasso ----
resultados_lasso = []

for a in alpha_range:
    for max_iter in max_iter_range:
        model_lasso = Lasso(alpha=a, max_iter=max_iter, random_state=0)
        model_lasso.fit(x_train, y_train)

        y_pred = model_lasso.predict(x_val)

        resultados_lasso.append({
            'alpha': a,
            'max_iter': max_iter,
            'R2': mt.r2_score(y_val, y_pred),
            'MSE': mt.mean_squared_error(y_val, y_pred),
            'RMSE': np.sqrt(mt.mean_squared_error(y_val, y_pred)),
            'MAE': mt.mean_absolute_error(y_val, y_pred),
            'MAPE': mt.mean_absolute_percentage_error(y_val, y_pred)
        })

tabela_lasso = pd.DataFrame(resultados_lasso)

# ---- Ridge ----
resultados_ridge = []

for a in alpha_range:
    for max_iter in max_iter_range:
        model_ridge = Ridge(alpha=a, max_iter=max_iter, random_state=0)
        model_ridge.fit(x_train, y_train)

        y_pred = model_ridge.predict(x_val)

        resultados_ridge.append({
            'alpha': a,
            'max_iter': max_iter,
            'R2': mt.r2_score(y_val, y_pred),
            'MSE': mt.mean_squared_error(y_val, y_pred),
            'RMSE': np.sqrt(mt.mean_squared_error(y_val, y_pred)),
            'MAE': mt.mean_absolute_error(y_val, y_pred),
            'MAPE': mt.mean_absolute_percentage_error(y_val, y_pred)
        })

tabela_ridge = pd.DataFrame(resultados_ridge)

In [13]:
tabela_lasso

,alpha,max_iter,R2,MSE,RMSE,MAE,MAPE
0,0.001,100,3.993646e-02,458.441490,21.411247,17.039476,8.682905
1,0.001,500,3.993646e-02,458.441490,21.411247,17.039476,8.682905
2,0.001,1000,3.993646e-02,458.441490,21.411247,17.039476,8.682905
3,0.001,5000,3.993646e-02,458.441490,21.411247,17.039476,8.682905
4,0.010,100,3.992825e-02,458.445407,21.411338,17.038243,8.686215
5,0.010,500,3.992825e-02,458.445407,21.411338,17.038243,8.686215
6,0.010,1000,3.992825e-02,458.445407,21.411338,17.038243,8.686215
7,0.010,5000,3.992825e-02,458.445407,21.411338,17.038243,8.686215
8,0.100,100,3.719533e-02,459.750411,21.441791,17.047448,8.686903
9,0.100,500,3.719533e-02,459.750411,21.441791,17.047448,8.686903
10,0.100,1000,3.719533e-02,459.750411,21.441791,17.047448,8.686903
11,0.100,5000,3.719533e-02,459.750411,21.441791,17.047448,8.686903
12,1.000,100,7.883643e-03,473.747081,21.765732,17.264922,8.695808
13,1.000,500,7.883643e-03,473.747081,21.765732,17.264922,8.695808
14,1.000,1000,7.883643e-03,473.747081,21.765732,17.264922,8.695808
15,1.000,5000,7.883643e-03,473.747081,21.765732,17.264922,8.695808
16,10.000,100,-7.197077e-07,477.511956,21.852047,17.352836,8.678722
17,10.000,500,-7.197077e-07,477.511956,21.852047,17.352836,8.678722
18,10.000,1000,-7.197077e-07,477.511956,21.852047,17.352836,8.678722
19,10.000,5000,-7.197077e-07,477.511956,21.852047,17.352836,8.678722
20,100.000,100,-7.197077e-07,477.511956,21.852047,17.352836,8.678722
21,100.000,500,-7.197077e-07,477.511956,21.852047,17.352836,8.678722
22,100.000,1000,-7.197077e-07,477.511956,21.852047,17.352836,8.678722
23,100.000,5000,-7.197077e-07,477.511956,21.852047,17.352836,8.678722

In [14]:
tabela_ridge

      alpha  max_iter        R2         MSE       RMSE        MAE      MAPE
0     0.001       100  0.039925  458.447040  21.411376  17.039753  8.682542
1     0.001       500  0.039925  458.447040  21.411376  17.039753  8.682542
2     0.001      1000  0.039925  458.447040  21.411376  17.039753  8.682542
3     0.001      5000  0.039925  458.447040  21.411376  17.039753  8.682542
4     0.010       100  0.039925  458.447025  21.411376  17.039751  8.682541
5     0.010       500  0.039925  458.447025  21.411376  17.039751  8.682541
6     0.010      1000  0.039925  458.447025  21.411376  17.039751  8.682541
7     0.010      5000  0.039925  458.447025  21.411376  17.039751  8.682541
8     0.100       100  0.039925  458.446874  21.411373  17.039725  8.682529
9     0.100       500  0.039925  458.446874  21.411373  17.039725  8.682529
10    0.100      1000  0.039925  458.446874  21.411373  17.039725  8.682529
11    0.100      5000  0.039925  458.446874  21.411373  17.039725  8.682529
12    1.000       100  0.039928  458.445477  21.411340  17.039472  8.682412
13    1.000       500  0.039928  458.445477  21.411340  17.039472  8.682412
14    1.000      1000  0.039928  458.445477  21.411340  17.039472  8.682412
15    1.000      5000  0.039928  458.445477  21.411340  17.039472  8.682412
16   10.000       100  0.039937  458.441098  21.411238  17.037610  8.681342
17   10.000       500  0.039937  458.441098  21.411238  17.037610  8.681342
18   10.000      1000  0.039937  458.441098  21.411238  17.037610  8.681342
19   10.000      5000  0.039937  458.441098  21.411238  17.037610  8.681342
20  100.000       100  0.038881  458.945555  21.423015  17.034553  8.674899
21  100.000       500  0.038881  458.945555  21.423015  17.034553  8.674899
22  100.000      1000  0.038881  458.945555  21.423015  17.034553  8.674899
23  100.000      5000  0.038881  458.945555  21.423015  17.034553  8.674899

In [15]:
#treinando com os melhores parâmetros: alpha=10 e max_iter=100

# ---- Lasso ----

model_lasso = Lasso(alpha=10, max_iter=100, random_state=0)
model_lasso.fit(x_train, y_train)

y_pred = model_lasso.predict(x_val)

resultados_lasso = ({
    'R2': [mt.r2_score(y_val, y_pred)],
    'MSE': [mt.mean_squared_error(y_val, y_pred)],
    'RMSE': [np.sqrt(mt.mean_squared_error(y_val, y_pred))],
    'MAE': [mt.mean_absolute_error(y_val, y_pred)],
    'MAPE':[ mt.mean_absolute_percentage_error(y_val, y_pred)]
})

tabela_lasso = pd.DataFrame(resultados_lasso)

# ---- Ridge ----

model_ridge = Ridge(alpha=10, max_iter=100, random_state=0)
model_ridge.fit(x_train, y_train)

y_pred = model_ridge.predict(x_val)

resultados_ridge = ({
    'R2': [mt.r2_score(y_val, y_pred)],
    'MSE': [mt.mean_squared_error(y_val, y_pred)],
    'RMSE': [np.sqrt(mt.mean_squared_error(y_val, y_pred))],
    'MAE': [mt.mean_absolute_error(y_val, y_pred)],
    'MAPE': [mt.mean_absolute_percentage_error(y_val, y_pred)]
})

tabela_ridge = pd.DataFrame(resultados_ridge)

In [16]:
tabela_lasso.round(3)

    R2      MSE    RMSE     MAE   MAPE
0 -0.0  477.512  21.852  17.353  8.679

In [17]:
tabela_ridge.round(3)

     R2      MSE    RMSE     MAE   MAPE
0  0.04  458.441  21.411  17.038  8.681

### LR - Train

In [18]:
#treinando com os melhores parâmetros: alpha=10 e max_iter=100

# ---- Lasso ----

model_lasso = Lasso(alpha=10, max_iter=100, random_state=0)
model_lasso.fit(x_train, y_train)

y_pred = model_lasso.predict(x_train)

resultados_lasso = ({
    'R2': [mt.r2_score(y_train, y_pred)],
    'MSE': [mt.mean_squared_error(y_train, y_pred)],
    'RMSE': [np.sqrt(mt.mean_squared_error(y_train, y_pred))],
    'MAE': [mt.mean_absolute_error(y_train, y_pred)],
    'MAPE':[ mt.mean_absolute_percentage_error(y_train, y_pred)]
})

tabela_lasso = pd.DataFrame(resultados_lasso)

# ---- Ridge ----

model_ridge = Ridge(alpha=10, max_iter=100, random_state=0)
model_ridge.fit(x_train, y_train)

y_pred = model_ridge.predict(x_train)

resultados_ridge = ({
    'R2': [mt.r2_score(y_train, y_pred)],
    'MSE': [mt.mean_squared_error(y_train, y_pred)],
    'RMSE': [np.sqrt(mt.mean_squared_error(y_train, y_pred))],
    'MAE': [mt.mean_absolute_error(y_train, y_pred)],
    'MAPE': [mt.mean_absolute_percentage_error(y_train, y_pred)]
})

tabela_ridge = pd.DataFrame(resultados_ridge)

In [19]:
tabela_lasso.round(3)

    R2      MSE    RMSE     MAE   MAPE
0  0.0  478.013  21.863  17.365  8.742

In [20]:
tabela_ridge.round(3)

      R2     MSE    RMSE     MAE   MAPE
0  0.046  456.02  21.355  16.999  8.655

### LR - Test

In [21]:
#treinando com os melhores parâmetros: alpha=10 e max_iter=100

# ---- Lasso ----

model_lasso = Lasso(alpha=10, max_iter=100, random_state=0)
model_lasso.fit(x_train, y_train)

y_pred = model_lasso.predict(x_test)

resultados_lasso = ({
    'R2': [mt.r2_score(y_test, y_pred)],
    'MSE': [mt.mean_squared_error(y_test, y_pred)],
    'RMSE': [np.sqrt(mt.mean_squared_error(y_test, y_pred))],
    'MAE': [mt.mean_absolute_error(y_test, y_pred)],
    'MAPE':[ mt.mean_absolute_percentage_error(y_test, y_pred)]
})

tabela_lasso = pd.DataFrame(resultados_lasso)

# ---- Ridge ----

model_ridge = Ridge(alpha=10, max_iter=100, random_state=0)
model_ridge.fit(x_train, y_train)

y_pred = model_ridge.predict(x_test)

resultados_ridge = ({
    'R2': [mt.r2_score(y_test, y_pred)],
    'MSE': [mt.mean_squared_error(y_test, y_pred)],
    'RMSE': [np.sqrt(mt.mean_squared_error(y_test, y_pred))],
    'MAE': [mt.mean_absolute_error(y_test, y_pred)],
    'MAPE': [mt.mean_absolute_percentage_error(y_test, y_pred)]
})

tabela_ridge = pd.DataFrame(resultados_ridge)

In [22]:
tabela_lasso.round(3)

    R2      MSE    RMSE     MAE   MAPE
0 -0.0  486.961  22.067  17.551  8.715

In [23]:
tabela_ridge.round(3)

      R2      MSE    RMSE     MAE   MAPE
0  0.052  461.495  21.482  17.128  8.531

# Linear Regression - Elastic Net

Parâmetros: aplha, l1_ratio e max_iter

### LR - Val

In [24]:
#encontrando os melhores parametros

alpha_range = [0.001, 0.01, 0.1, 1, 10, 100]
l1_ratio_range = [0.1, 0.3, 0.5, 0.7, 0.9]
max_iter_range = [100, 500, 1000, 5000]

# ---- Elastic Net ----
resultados_elastic = []

for a in alpha_range:
    for l1 in l1_ratio_range:
        for max_iter in max_iter_range:
            model_elastic = ElasticNet(alpha=a, l1_ratio=l1, max_iter=max_iter, random_state=0)
            model_elastic.fit(x_train, y_train)

            y_pred = model_elastic.predict(x_val)

            resultados_elastic.append({
                'alpha': a,
                'l1_ratio': l1,
                'max_iter': max_iter,
                'R2': mt.r2_score(y_val, y_pred),
                'MSE': mt.mean_squared_error(y_val, y_pred),
                'RMSE': np.sqrt(mt.mean_squared_error(y_val, y_pred)),
                'MAE': mt.mean_absolute_error(y_val, y_pred),
                'MAPE': mt.mean_absolute_percentage_error(y_val, y_pred)
            })

tabela_elastic = pd.DataFrame(resultados_elastic)

In [25]:
tabela_elastic.round(3).sort_values(by='R2', ascending=False).head(30)

    alpha  l1_ratio  max_iter    R2      MSE    RMSE     MAE   MAPE
0   0.001       0.1       100  0.04  458.441  21.411  17.038  8.681
1   0.001       0.1       500  0.04  458.441  21.411  17.038  8.681
2   0.001       0.1      1000  0.04  458.441  21.411  17.038  8.681
3   0.001       0.1      5000  0.04  458.441  21.411  17.038  8.681
4   0.001       0.3       100  0.04  458.440  21.411  17.038  8.682
5   0.001       0.3       500  0.04  458.440  21.411  17.038  8.682
6   0.001       0.3      1000  0.04  458.440  21.411  17.038  8.682
7   0.001       0.3      5000  0.04  458.440  21.411  17.038  8.682
8   0.001       0.5       100  0.04  458.440  21.411  17.038  8.682
9   0.001       0.5       500  0.04  458.440  21.411  17.038  8.682
10  0.001       0.5      1000  0.04  458.440  21.411  17.038  8.682
11  0.001       0.5      5000  0.04  458.440  21.411  17.038  8.682
12  0.001       0.7       100  0.04  458.440  21.411  17.039  8.682
13  0.001       0.7       500  0.04  458.440  21.411  17.039  8.682
14  0.001       0.7      1000  0.04  458.440  21.411  17.039  8.682
15  0.001       0.7      5000  0.04  458.440  21.411  17.039  8.682
16  0.001       0.9       100  0.04  458.441  21.411  17.039  8.683
17  0.001       0.9       500  0.04  458.441  21.411  17.039  8.683
18  0.001       0.9      1000  0.04  458.441  21.411  17.039  8.683
19  0.001       0.9      5000  0.04  458.441  21.411  17.039  8.683
28  0.010       0.5       100  0.04  458.632  21.416  17.034  8.679
29  0.010       0.5       500  0.04  458.632  21.416  17.034  8.679
30  0.010       0.5      1000  0.04  458.632  21.416  17.034  8.679
31  0.010       0.5      5000  0.04  458.632  21.416  17.034  8.679
36  0.010       0.9       100  0.04  458.463  21.412  17.037  8.684
37  0.010       0.9       500  0.04  458.463  21.412  17.037  8.684
38  0.010       0.9      1000  0.04  458.463  21.412  17.037  8.684
39  0.010       0.9      5000  0.04  458.463  21.412  17.037  8.684
35  0.010       0.7      5000  0.04  458.529  21.413  17.035  8.682
34  0.010       0.7      1000  0.04  458.529  21.413  17.035  8.682

In [26]:
#treinando com os melhores parâmetros: alpha=SEU_ALPHA, l1_ratio=SEU_L1_RATIO e max_iter=SEU_MAX_ITER

# ---- Elastic Net ----

model_elastic = ElasticNet(alpha=0.001, l1_ratio=0.1, max_iter=100, random_state=0)
model_elastic.fit(x_train, y_train)

y_pred = model_elastic.predict(x_val)

resultados_elastic = ({
    'R2': [mt.r2_score(y_val, y_pred)],
    'MSE': [mt.mean_squared_error(y_val, y_pred)],
    'RMSE': [np.sqrt(mt.mean_squared_error(y_val, y_pred))],
    'MAE': [mt.mean_absolute_error(y_val, y_pred)],
    'MAPE': [mt.mean_absolute_percentage_error(y_val, y_pred)]
})

tabela_elastic = pd.DataFrame(resultados_elastic)

In [27]:
tabela_elastic.round(3)

     R2      MSE    RMSE     MAE   MAPE
0  0.04  458.441  21.411  17.038  8.681

### LR - Train

In [28]:
#treinando com os melhores parâmetros: alpha=SEU_ALPHA, l1_ratio=SEU_L1_RATIO e max_iter=SEU_MAX_ITER

# ---- Elastic Net ----

model_elastic = ElasticNet(alpha=0.001, l1_ratio=0.1, max_iter=100, random_state=0)
model_elastic.fit(x_train, y_train)

y_pred = model_elastic.predict(x_train)

resultados_elastic = ({
    'R2': [mt.r2_score(y_train, y_pred)],
    'MSE': [mt.mean_squared_error(y_train, y_pred)],
    'RMSE': [np.sqrt(mt.mean_squared_error(y_train, y_pred))],
    'MAE': [mt.mean_absolute_error(y_train, y_pred)],
    'MAPE': [mt.mean_absolute_percentage_error(y_train, y_pred)]
})

tabela_elastic = pd.DataFrame(resultados_elastic)

In [29]:
tabela_elastic.round(3)

      R2      MSE    RMSE     MAE   MAPE
0  0.046  456.018  21.355  16.999  8.655

### LR - Test

In [30]:
#treinando com os melhores parâmetros: alpha=SEU_ALPHA, l1_ratio=SEU_L1_RATIO e max_iter=SEU_MAX_ITER

# ---- Elastic Net ----

model_elastic = ElasticNet(alpha=0.001, l1_ratio=0.1, max_iter=100, random_state=0)
model_elastic.fit(x_train, y_train)

y_pred = model_elastic.predict(x_test)

resultados_elastic = ({
    'R2': [mt.r2_score(y_test, y_pred)],
    'MSE': [mt.mean_squared_error(y_test, y_pred)],
    'RMSE': [np.sqrt(mt.mean_squared_error(y_test, y_pred))],
    'MAE': [mt.mean_absolute_error(y_test, y_pred)],
    'MAPE': [mt.mean_absolute_percentage_error(y_test, y_pred)]
})

tabela_elastic = pd.DataFrame(resultados_elastic)

In [31]:
tabela_elastic.round(3)

      R2      MSE    RMSE     MAE  MAPE
0  0.052  461.492  21.482  17.128  8.53

# Decision Tree Regression

Parâmetros: max_depth

### DT - Val

In [32]:
#achando o melhor parametro
max_depth_range = np.arange(2, 21, 2)

resultados_dt = []

for d in max_depth_range:
    model_dt = DecisionTreeRegressor(max_depth=d, random_state=0)
    model_dt.fit(x_train, y_train)

    y_pred = model_dt.predict(x_val)

    resultados_dt.append({
        'max_depth': d,
        'R2': mt.r2_score(y_val, y_pred),
        'MSE': mt.mean_squared_error(y_val, y_pred),
        'RMSE': np.sqrt(mt.mean_squared_error(y_val, y_pred)),
        'MAE': mt.mean_absolute_error(y_val, y_pred),
        'MAPE': mt.mean_absolute_percentage_error(y_val, y_pred)
    })

tabela_dt = pd.DataFrame(resultados_dt)
tabela_dt

   max_depth        R2         MSE       RMSE        MAE      MAPE
0          2  0.037609  459.552983  21.437187  16.985102  8.480125
1          4  0.062168  447.825853  21.161896  16.849288  8.536141
2          6  0.063296  447.286802  21.149156  16.748081  8.324423
3          8  0.034896  460.848567  21.467384  16.890528  7.950885
4         10 -0.005483  480.129882  21.911866  16.879492  7.894165
5         12 -0.063329  507.752022  22.533354  16.989090  7.882661
6         14 -0.124421  536.924198  23.171625  17.002017  7.758598
7         16 -0.167414  557.453676  23.610457  17.007334  7.575919
8         18 -0.211798  578.647575  24.055095  16.979212  7.261401
9         20 -0.261266  602.269281  24.541175  17.076967  7.195753

In [33]:
tabela_dt.loc[tabela_dt['R2'].idxmax()]

max_depth      6.000000
R2             0.063296
MSE          447.286802
RMSE          21.149156
MAE           16.748081
MAPE           8.324423
Name: 2, dtype: float64

In [34]:
#treinando o modelo com os melhores parâmetros

model_dt = DecisionTreeRegressor(max_depth=6)
model_dt.fit(x_train, y_train)

y_pred = model_dt.predict(x_val)

resultados_final = ({
        'R2': mt.r2_score(y_val, y_pred),
        'MSE': mt.mean_squared_error(y_val, y_pred),
        'RMSE': np.sqrt(mt.mean_squared_error(y_val, y_pred)),
        'MAE': mt.mean_absolute_error(y_val, y_pred),
        'MAPE': mt.mean_absolute_percentage_error(y_val, y_pred)
    })

resultados_final = pd.DataFrame([resultados_final])
resultados_final

         R2         MSE       RMSE        MAE      MAPE
0  0.063296  447.286802  21.149156  16.748081  8.324423

### DT - Train

In [35]:
#treinando o modelo com os melhores parâmetros

model_dt = DecisionTreeRegressor(max_depth=6)
model_dt.fit(x_train, y_train)

y_pred = model_dt.predict(x_train)

resultados_final = ({
        'R2': mt.r2_score(y_train, y_pred),
        'MSE': mt.mean_squared_error(y_train, y_pred),
        'RMSE': np.sqrt(mt.mean_squared_error(y_train, y_pred)),
        'MAE': mt.mean_absolute_error(y_train, y_pred),
        'MAPE': mt.mean_absolute_percentage_error(y_train, y_pred)
    })

resultados_final = pd.DataFrame([resultados_final])
resultados_final

         R2         MSE       RMSE        MAE      MAPE
0  0.144608  408.887912  20.220977  16.026872  7.307613

### DT - Test

In [36]:
#treinando o modelo com os melhores parâmetros

model_dt = DecisionTreeRegressor(max_depth=6)
model_dt.fit(x_train, y_train)

y_pred = model_dt.predict(x_test)

resultados_final = ({
        'R2': mt.r2_score(y_test, y_pred),
        'MSE': mt.mean_squared_error(y_test, y_pred),
        'RMSE': np.sqrt(mt.mean_squared_error(y_test, y_pred)),
        'MAE': mt.mean_absolute_error(y_test, y_pred),
        'MAPE': mt.mean_absolute_percentage_error(y_test, y_pred)
    })

resultados_final = pd.DataFrame([resultados_final])
resultados_final

         R2         MSE       RMSE        MAE      MAPE
0  0.078494  448.681971  21.182114  16.893201  7.606125

# Random Forest Regression

Parâmetros: n_estimators e max_depth

### RF - Val

In [37]:
#achando os melhores parametros para Random Forest Regression
from sklearn.ensemble import RandomForestRegressor

n_estimators_range = np.arange(50, 501, 100)
max_depth_range = np.arange(2, 21, 4)

resultados_rf = []

for n in n_estimators_range:
    for d in max_depth_range:
        model_rf = RandomForestRegressor(n_estimators=n, max_depth=d, random_state=0, n_jobs=-1)
        model_rf.fit(x_train, y_train)

        y_pred = model_rf.predict(x_val)

        resultados_rf.append({
            'n_estimators': n,
            'max_depth': d,
            'R2': mt.r2_score(y_val, y_pred),
            'MSE': mt.mean_squared_error(y_val, y_pred),
            'RMSE': np.sqrt(mt.mean_squared_error(y_val, y_pred)),
            'MAE': mt.mean_absolute_error(y_val, y_pred),
            'MAPE': mt.mean_absolute_percentage_error(y_val, y_pred)
        })

tabela_rf = pd.DataFrame(resultados_rf)

/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [38]:
melhores_indices = tabela_rf.loc[tabela_rf['R2'].idxmax()]
melhores_indices

n_estimators    350.000000
max_depth        18.000000
R2                0.331829
MSE             319.059390
RMSE             17.862234
MAE              13.292274
MAPE              7.108431
Name: 19, dtype: float64

In [39]:
#Prevendo com os melhores parametros

model_rf = RandomForestRegressor(n_estimators=n, max_depth=d, random_state=0, n_jobs=-1)
model_rf.fit(x_train, y_train)

y_pred = model_rf.predict(x_val)

resultado_final = ({
    'R2': mt.r2_score(y_val, y_pred),
    'MSE': mt.mean_squared_error(y_val, y_pred),
    'RMSE': np.sqrt(mt.mean_squared_error(y_val, y_pred)),
    'MAE': mt.mean_absolute_error(y_val, y_pred),
    'MAPE': mt.mean_absolute_percentage_error(y_val, y_pred)
})

tabela_rf = pd.DataFrame([resultado_final])
tabela_rf

/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

         R2         MSE       RMSE        MAE      MAPE
0  0.330211  319.832036  17.883848  13.311389  7.132564

### RF - Train

In [40]:
#Prevendo com os melhores parametros

model_rf = RandomForestRegressor(n_estimators=n, max_depth=d, random_state=0, n_jobs=-1)
model_rf.fit(x_train, y_train)

y_pred = model_rf.predict(x_train)

resultado_final = ({
    'R2': mt.r2_score(y_train, y_pred),
    'MSE': mt.mean_squared_error(y_train, y_pred),
    'RMSE': np.sqrt(mt.mean_squared_error(y_train, y_pred)),
    'MAE': mt.mean_absolute_error(y_train, y_pred),
    'MAPE': mt.mean_absolute_percentage_error(y_train, y_pred)
})

tabela_rf = pd.DataFrame([resultado_final])
tabela_rf

/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

         R2        MSE      RMSE       MAE      MAPE
0  0.862045  65.944066  8.120595  6.144241  2.954035

### RF - Test

In [41]:
#Prevendo com os melhores parametros

model_rf = RandomForestRegressor(n_estimators=n, max_depth=d, random_state=0, n_jobs=-1)
model_rf.fit(x_train, y_train)

y_pred = model_rf.predict(x_test)

resultado_final = ({
    'R2': mt.r2_score(y_test, y_pred),
    'MSE': mt.mean_squared_error(y_test, y_pred),
    'RMSE': np.sqrt(mt.mean_squared_error(y_test, y_pred)),
    'MAE': mt.mean_absolute_error(y_test, y_pred),
    'MAPE': mt.mean_absolute_percentage_error(y_test, y_pred)
})

tabela_rf = pd.DataFrame([resultado_final])
tabela_rf

/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

         R2         MSE       RMSE        MAE     MAPE
0  0.349919  316.524986  17.791149  13.354039  6.60949

# Polinomial Regression 

Parâmetro: degree

### PR  - Val

In [42]:
#treinando o melhor parâmetro

degree_range = np.arange(1, 6, 1)   # graus baixos — cresce muito rápido em número de colunas

resultados_poly = []

for d in degree_range:
    poly = PolynomialFeatures(degree=d)
    x_train_poly = poly.fit_transform(x_train)
    x_val_poly = poly.transform(x_val)

    model_poly = LinearRegression()
    model_poly.fit(x_train_poly, y_train)

    y_pred = model_poly.predict(x_val_poly)

    resultados_poly.append({
        'degree': d,
        'R2': mt.r2_score(y_val, y_pred),
        'MSE': mt.mean_squared_error(y_val, y_pred),
        'RMSE': np.sqrt(mt.mean_squared_error(y_val, y_pred)),
        'MAE': mt.mean_absolute_error(y_val, y_pred),
        'MAPE': mt.mean_absolute_percentage_error(y_val, y_pred)
    })

tabela_poly = pd.DataFrame(resultados_poly)

In [43]:
melhores_parametros = tabela_poly.loc[tabela_poly['R2'].idxmax()]
melhores_parametros

degree      2.000000
R2          0.066477
MSE       445.768223
RMSE       21.113224
MAE        16.749939
MAPE        8.547931
Name: 1, dtype: float64

In [44]:
#Prevendo dados val com os melhores parametros
poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_val_poly = poly.transform(x_val)

model_poly = LinearRegression()
model_poly.fit(x_train_poly, y_train)

y_pred = model_poly.predict(x_val_poly)

resultado_final = ({
    'R2': mt.r2_score(y_val, y_pred),
    'MSE': mt.mean_squared_error(y_val, y_pred),
    'RMSE': np.sqrt(mt.mean_squared_error(y_val, y_pred)),
    'MAE': mt.mean_absolute_error(y_val, y_pred),
    'MAPE': mt.mean_absolute_percentage_error(y_val, y_pred)
})

resultado_final = pd.DataFrame([resultado_final])
resultado_final

         R2         MSE       RMSE        MAE      MAPE
0  0.066477  445.768223  21.113224  16.749939  8.547931

### PR - Train

In [45]:
#Prevendo dados train com os melhores parametros
poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_train_poly = poly.transform(x_train)

model_poly = LinearRegression()
model_poly.fit(x_train_poly, y_train)

y_pred = model_poly.predict(x_train_poly)

resultado_final = ({
    'R2': mt.r2_score(y_train, y_pred),
    'MSE': mt.mean_squared_error(y_train, y_pred),
    'RMSE': np.sqrt(mt.mean_squared_error(y_train, y_pred)),
    'MAE': mt.mean_absolute_error(y_train, y_pred),
    'MAPE': mt.mean_absolute_percentage_error(y_train, y_pred)
})

resultado_final = pd.DataFrame([resultado_final])
resultado_final

         R2        MSE       RMSE        MAE     MAPE
0  0.094195  432.98621  20.808321  16.458032  8.35054

### PR - Test

In [46]:
#Prevendo dados test com os melhores parametros
poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_test_poly = poly.transform(x_test)

model_poly = LinearRegression()
model_poly.fit(x_train_poly, y_train)

y_pred = model_poly.predict(x_test_poly)

resultado_final = ({
    'R2': mt.r2_score(y_test, y_pred),
    'MSE': mt.mean_squared_error(y_test, y_pred),
    'RMSE': np.sqrt(mt.mean_squared_error(y_test, y_pred)),
    'MAE': mt.mean_absolute_error(y_test, y_pred),
    'MAPE': mt.mean_absolute_percentage_error(y_test, y_pred)
})

resultado_final = pd.DataFrame([resultado_final])
resultado_final

         R2         MSE       RMSE        MAE      MAPE
0  0.090079  443.041256  21.048545  16.720535  8.242464

# Polinomial Regression Lasso e Ridge

Parâmetro: degree, alpha e max_iter

### PR - Val

In [47]:
#achando os melhores parametros
degree_range = np.arange(1, 4, 1)
alpha_range = [0.01, 0.1, 1, 10]
max_iter_range = [5000]

# ---- Polynomial + Lasso ----
resultados_poly_lasso = []

for d in degree_range:
    poly = PolynomialFeatures(degree=d)
    x_train_poly = poly.fit_transform(x_train)
    x_val_poly = poly.transform(x_val)

    for a in alpha_range:
        for max_iter in max_iter_range:
            model_lasso = Lasso(alpha=a, max_iter=max_iter, random_state=0)
            model_lasso.fit(x_train_poly, y_train)

            y_pred = model_lasso.predict(x_val_poly)

            resultados_poly_lasso.append({
                'degree': d,
                'alpha': a,
                'max_iter': max_iter,
                'R2': mt.r2_score(y_val, y_pred),
                'MSE': mt.mean_squared_error(y_val, y_pred),
                'RMSE': np.sqrt(mt.mean_squared_error(y_val, y_pred)),
                'MAE': mt.mean_absolute_error(y_val, y_pred),
                'MAPE': mt.mean_absolute_percentage_error(y_val, y_pred)
            })

tabela_poly_lasso = pd.DataFrame(resultados_poly_lasso)

# ---- Polynomial + Ridge ----
resultados_poly_ridge = []

for d in degree_range:
    poly = PolynomialFeatures(degree=d)
    x_train_poly = poly.fit_transform(x_train)
    x_val_poly = poly.transform(x_val)

    for a in alpha_range:
        for max_iter in max_iter_range:
            model_ridge = Ridge(alpha=a, max_iter=max_iter, random_state=0)
            model_ridge.fit(x_train_poly, y_train)

            y_pred = model_ridge.predict(x_val_poly)

            resultados_poly_ridge.append({
                'degree': d,
                'alpha': a,
                'max_iter': max_iter,
                'R2': mt.r2_score(y_val, y_pred),
                'MSE': mt.mean_squared_error(y_val, y_pred),
                'RMSE': np.sqrt(mt.mean_squared_error(y_val, y_pred)),
                'MAE': mt.mean_absolute_error(y_val, y_pred),
                'MAPE': mt.mean_absolute_percentage_error(y_val, y_pred)
            })

tabela_poly_ridge = pd.DataFrame(resultados_poly_ridge)

In [48]:
tabela_poly_lasso.loc[tabela_poly_ridge['R2'].idxmax()]

degree         2.000000
alpha          1.000000
max_iter    5000.000000
R2             0.009631
MSE          472.912694
RMSE          21.746556
MAE           17.238379
MAPE           8.681847
Name: 6, dtype: float64

In [49]:
tabela_poly_ridge.loc[tabela_poly_ridge['R2'].idxmax()]

degree         2.000000
alpha          1.000000
max_iter    5000.000000
R2             0.067699
MSE          445.184410
RMSE          21.099394
MAE           16.738741
MAPE           8.568992
Name: 6, dtype: float64

In [55]:
#prevendo os melhores parâmetros com val

# ---- Polynomial + Lasso ----

poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_val_poly = poly.transform(x_val)


model_lasso = Lasso(alpha=1, max_iter=5000, random_state=0)
model_lasso.fit(x_train_poly, y_train)

y_pred = model_lasso.predict(x_val_poly)

resultados_poly_lasso = ({
    'R2': mt.r2_score(y_val, y_pred),
    'MSE': mt.mean_squared_error(y_val, y_pred),
    'RMSE': np.sqrt(mt.mean_squared_error(y_val, y_pred)),
    'MAE': mt.mean_absolute_error(y_val, y_pred),
    'MAPE': mt.mean_absolute_percentage_error(y_val, y_pred)
})

tabela_poly_lasso = pd.DataFrame([resultados_poly_lasso])

# ---- Polynomial + Ridge ----

poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_val_poly = poly.transform(x_val)


model_ridge = Ridge(alpha=1, max_iter=5000, random_state=0)
model_ridge.fit(x_train_poly, y_train)

y_pred = model_ridge.predict(x_val_poly)

resultados_poly_ridge = ({
    'R2': mt.r2_score(y_val, y_pred),
    'MSE': mt.mean_squared_error(y_val, y_pred),
    'RMSE': np.sqrt(mt.mean_squared_error(y_val, y_pred)),
    'MAE': mt.mean_absolute_error(y_val, y_pred),
    'MAPE': mt.mean_absolute_percentage_error(y_val, y_pred)
})

tabela_poly_ridge = pd.DataFrame([resultados_poly_ridge])

In [56]:
tabela_poly_lasso

         R2         MSE       RMSE        MAE      MAPE
0  0.009631  472.912694  21.746556  17.238379  8.681847

In [57]:
tabela_poly_ridge

         R2        MSE       RMSE        MAE      MAPE
0  0.067699  445.18441  21.099394  16.738741  8.568992

### PR - Train

In [52]:
#prevendo os melhores parâmetros com train

# ---- Polynomial + Lasso ----


poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_train_poly = poly.transform(x_train)


model_lasso = Lasso(alpha=1, max_iter=5000, random_state=0)
model_lasso.fit(x_train_poly, y_train)

y_pred = model_lasso.predict(x_train_poly)

resultados_poly_lasso = ({
    'R2': mt.r2_score(y_train, y_pred),
    'MSE': mt.mean_squared_error(y_train, y_pred),
    'RMSE': np.sqrt(mt.mean_squared_error(y_train, y_pred)),
    'MAE': mt.mean_absolute_error(y_train, y_pred),
    'MAPE': mt.mean_absolute_percentage_error(y_train, y_pred)
})

tabela_poly_lasso = pd.DataFrame([resultados_poly_lasso])

# ---- Polynomial + Ridge ----

poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_train_poly = poly.transform(x_train)


model_ridge = Ridge(alpha=1, max_iter=5000, random_state=0)
model_ridge.fit(x_train_poly, y_train)

y_pred = model_ridge.predict(x_train_poly)

resultados_poly_ridge = ({
    'R2': mt.r2_score(y_train, y_pred),
    'MSE': mt.mean_squared_error(y_train, y_pred),
    'RMSE': np.sqrt(mt.mean_squared_error(y_train, y_pred)),
    'MAE': mt.mean_absolute_error(y_train, y_pred),
    'MAPE': mt.mean_absolute_percentage_error(y_train, y_pred)
})

tabela_poly_ridge = pd.DataFrame([resultados_poly_ridge])

In [53]:
tabela_poly_lasso

        R2         MSE       RMSE       MAE      MAPE
0  0.00915  473.638776  21.763244  17.28545  8.699701

In [54]:
tabela_poly_ridge

         R2         MSE       RMSE        MAE      MAPE
0  0.093171  433.475457  20.820073  16.471972  8.372689

### PR - Test

In [58]:
#prevendo os melhores parâmetros com train

# ---- Polynomial + Lasso ----


poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_test_poly = poly.transform(x_test)


model_lasso = Lasso(alpha=1, max_iter=5000, random_state=0)
model_lasso.fit(x_train_poly, y_train)

y_pred = model_lasso.predict(x_test_poly)

resultados_poly_lasso = ({
    'R2': mt.r2_score(y_test, y_pred),
    'MSE': mt.mean_squared_error(y_test, y_pred),
    'RMSE': np.sqrt(mt.mean_squared_error(y_test, y_pred)),
    'MAE': mt.mean_absolute_error(y_test, y_pred),
    'MAPE': mt.mean_absolute_percentage_error(y_test, y_pred)
})

tabela_poly_lasso = pd.DataFrame([resultados_poly_lasso])

# ---- Polynomial + Ridge ----

poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_test_poly = poly.transform(x_test)


model_ridge = Ridge(alpha=1, max_iter=5000, random_state=0)
model_ridge.fit(x_train_poly, y_train)

y_pred = model_ridge.predict(x_test_poly)

resultados_poly_ridge = ({
    'R2': mt.r2_score(y_test, y_pred),
    'MSE': mt.mean_squared_error(y_test, y_pred),
    'RMSE': np.sqrt(mt.mean_squared_error(y_test, y_pred)),
    'MAE': mt.mean_absolute_error(y_test, y_pred),
    'MAPE': mt.mean_absolute_percentage_error(y_test, y_pred)
})

tabela_poly_ridge = pd.DataFrame([resultados_poly_ridge])

In [59]:
tabela_poly_lasso

         R2         MSE       RMSE        MAE      MAPE
0  0.008372  482.824405  21.973266  17.456854  8.756072

In [60]:
tabela_poly_ridge

         R2       MSE       RMSE        MAE      MAPE
0  0.089167  443.4853  21.059091  16.728879  8.288682

# Polinomial Regression Elastic Net

Parâmetro: degree, alpha, l1_ratio, max_iter

### PR - Val

In [61]:
#definindo os melhores parametros
degree_range = np.arange(1, 4, 1)      # 1, 2, 3
alpha_range = [0.01, 0.1, 1, 10]       # 4 valores
l1_ratio_range = [0.1, 0.5, 0.9]       # 3 valores — L2-dominante, equilibrado, L1-dominante
max_iter_range = [5000]                 # 1 valor só, já alto o suficiente

resultados_poly_elastic = []

for d in degree_range:
    poly = PolynomialFeatures(degree=d)
    x_train_poly = poly.fit_transform(x_train)
    x_val_poly = poly.transform(x_val)

    for a in alpha_range:
        for l1 in l1_ratio_range:
            for max_iter in max_iter_range:
                model_elastic = ElasticNet(alpha=a, l1_ratio=l1, max_iter=max_iter, random_state=0)
                model_elastic.fit(x_train_poly, y_train)

                y_pred = model_elastic.predict(x_val_poly)

                resultados_poly_elastic.append({
                    'degree': d,
                    'alpha': a,
                    'l1_ratio': l1,
                    'max_iter': max_iter,
                    'R2': mt.r2_score(y_val, y_pred),
                    'MSE': mt.mean_squared_error(y_val, y_pred),
                    'RMSE': np.sqrt(mt.mean_squared_error(y_val, y_pred)),
                    'MAE': mt.mean_absolute_error(y_val, y_pred),
                    'MAPE': mt.mean_absolute_percentage_error(y_val, y_pred)
                })

tabela_poly_elastic = pd.DataFrame(resultados_poly_elastic)

/home/lucas/.pyenv/versions/aulas_ml_env/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.120517e+03, tolerance: 5.042e+02
  model = cd_fast.enet_coordinate_descent(

In [63]:
melhores_parametros = tabela_poly_elastic.loc[tabela_poly_ridge['R2'].idxmax()]
melhores_parametros

degree         1.000000
alpha          0.010000
l1_ratio       0.100000
max_iter    5000.000000
R2             0.038947
MSE          458.913949
RMSE          21.422277
MAE           17.034414
MAPE           8.675405
Name: 0, dtype: float64

In [65]:
#prevendo com os melhores parametros
poly = PolynomialFeatures(degree=1)
x_train_poly = poly.fit_transform(x_train)
x_val_poly = poly.transform(x_val)


model_elastic = ElasticNet(alpha=0.01, l1_ratio=0.1, max_iter=5000, random_state=0)
model_elastic.fit(x_train_poly, y_train)

y_pred = model_elastic.predict(x_val_poly)

resultados_poly_elastic = ({
    'R2': mt.r2_score(y_val, y_pred),
    'MSE': mt.mean_squared_error(y_val, y_pred),
    'RMSE': np.sqrt(mt.mean_squared_error(y_val, y_pred)),
    'MAE': mt.mean_absolute_error(y_val, y_pred),
    'MAPE': mt.mean_absolute_percentage_error(y_val, y_pred)
})

tabela_poly_elastic = pd.DataFrame([resultados_poly_elastic])
tabela_poly_elastic

         R2         MSE       RMSE        MAE      MAPE
0  0.038947  458.913949  21.422277  17.034414  8.675405

### PR - Train

In [66]:
#prevendo com os melhores parametros
poly = PolynomialFeatures(degree=1)
x_train_poly = poly.fit_transform(x_train)
x_train_poly = poly.transform(x_train)


model_elastic = ElasticNet(alpha=0.01, l1_ratio=0.1, max_iter=5000, random_state=0)
model_elastic.fit(x_train_poly, y_train)

y_pred = model_elastic.predict(x_train_poly)

resultados_poly_elastic = ({
    'R2': mt.r2_score(y_train, y_pred),
    'MSE': mt.mean_squared_error(y_train, y_pred),
    'RMSE': np.sqrt(mt.mean_squared_error(y_train, y_pred)),
    'MAE': mt.mean_absolute_error(y_train, y_pred),
    'MAPE': mt.mean_absolute_percentage_error(y_train, y_pred)
})

tabela_poly_elastic = pd.DataFrame([resultados_poly_elastic])
tabela_poly_elastic

         R2         MSE       RMSE        MAE      MAPE
0  0.044084  456.939706  21.376148  17.015909  8.664276

### PR - Test

In [67]:
#prevendo com os melhores parametros
poly = PolynomialFeatures(degree=1)
x_train_poly = poly.fit_transform(x_train)
x_test_poly = poly.transform(x_test)


model_elastic = ElasticNet(alpha=0.01, l1_ratio=0.1, max_iter=5000, random_state=0)
model_elastic.fit(x_train_poly, y_train)

y_pred = model_elastic.predict(x_test_poly)

resultados_poly_elastic = ({
    'R2': mt.r2_score(y_test, y_pred),
    'MSE': mt.mean_squared_error(y_test, y_pred),
    'RMSE': np.sqrt(mt.mean_squared_error(y_test, y_pred)),
    'MAE': mt.mean_absolute_error(y_test, y_pred),
    'MAPE': mt.mean_absolute_percentage_error(y_test, y_pred)
})

tabela_poly_elastic = pd.DataFrame([resultados_poly_elastic])
tabela_poly_elastic

         R2         MSE       RMSE        MAE      MAPE
0  0.049068  463.009819  21.517663  17.141174  8.576846